### PR TITLE
Fix `readonly` brand not being stripped from `create` shape override

### LINKED ISSUE #132: Fix doing readonly on `id` causing issues with built-in methods
There have been some reports where marking id as readonly is causing runtime issues with the built in methods (such as `create` requiring `id` field when it shouldnt)

Marking `id` as readonly or not should not affect functionality of the library built-in methods.

`id` is already treated as readonly even if it is not marked. So The current work around for these bugs are just not wrapping `id` field with `readonly`.

### PR DESCRIPTION
**Pull request by lakardion**
## What this does
- Change the way `z.ZodBranded` is being checked. For some reason (which I am still not sure) the brand class type was removed at some point of the processing of the zod instance. This worked fine in React but in environments like Vue and RunJS this problem arose.

Closes #132

### CODE REVIEW

File: src/utils/api/api.ts [hunk 1]
```diff
@@ -171,14 +172,17 @@ export const removeReadonlyFields = <T extends z.ZodRawShape, TUnwrap extends (k
   shape: T,
   unwrap?: TUnwrap
 ) => {
-  const entries = Object.entries(shape).flatMap(([k, v]) => {
```
Comment (lakardion) [inline src/utils/api/api.ts:174]: Reworked this trying to avoid any incompatibility issues with flatMap but that seemed not to be the case

File: src/utils/api/api.ts [hunk 2]
```diff
@@ -171,14 +172,17 @@ export const removeReadonlyFields = <T extends z.ZodRawShape, TUnwrap extends (k
...
-    if (v instanceof z.ZodBranded && v.description === READONLY_TAG) {
```
Comment (lakardion) [inline src/utils/api/api.ts:175]: This was really confusing since the test passed properly but whenever running the library within vue/runjs this seemed to work differently.
React yielded `v instanceof z.ZodBranded` to be `true`
But Vue and RunJS would just say `false`
This just threw me off and made this quite hard to debug.
